import "@/app/assets/styles/global.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import FavoritesProvider from "@/app/providers/favorites";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-900 mb-6 p-6`}>
        <FavoritesProvider>
          <h1 className="text-3xl font-bold text-white mb-6 px-6 py-2">
            BitStarz
          </h1>
          {children}
        </FavoritesProvider>
      </body>
    </html>
  );
}
