import "@/app/assets/styles/global.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import FavoritesProvider from "@/app/providers/favorites";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FavoritesProvider>
          <p>apples</p>
          {children}
        </FavoritesProvider>
      </body>
    </html>
  );
}
